

# Site Settings
title:                      "2k15 Jekyll Theme"
email:                      "stefano.marra1987@gmail.com"
description:                "I’m Stefano: Full-stack Polyvalent Web Developer and Designer."
baseurl:                    "http://stefanomarra.github.io/2k15-jekyll-theme"
url:                        "http://stefanomarra.github.io/2k15-jekyll-theme"
logourl:                    "/assets/img/bloglogo.png"
paginate:                   5
paginate_path:              "/blog/page:num/"

# Author Settings
author_name:                "Stefano Marra"
author_url:                 "http://www.stefanomarra.com"
author_bio:                 "A Web Developer and Web Designer based in Rome, Italy"
author_email:               "stefano.marra1987@gmail.com"
author_image:               "/assets/img/authorimage.jpg"

# Social Settings
twitter_url:                "http://twitter.com"
facebook_url:               "http://facebook.com"
github_url:                 "http://github.com"
youtube_url:                "http://youtube.com"
dribbble_url:               "http://dribbble.com"
googleplus_url:             "http://google.com/plus"
instagram_url:              "http://instagram.com"
pinterest_url:              "http://pinterest.com"
linkedin_url:               "http://linkedin.com"

# Theme Settings
theme_disqus_shortname:     "stefanomarrablog"
theme_analytics_id:         "" # UA-65607011-1
theme_reading_time:         true

# Build Settings
#markdown:                   kramdown
gems:                       [jekyll-paginate]
markdown:                   kramdown
highlighter:                rouge

exclude: ["README.md", gulpfile.js", "Gemfile", "Gemfile.lock", "package.json", "node_modules"]