

# Site Settings
title: 						"Lion Code Studio"
email: 						"your-email@domain.com"
description: 				"Test theme for Jekyll blogging platform. It will be available on themeforest."
baseurl: 					""
url: 						"http://www.lioncodestudio.com"
logourl: 					"/assets/img/bloglogo.jpg"
paginate: 					5

# Author Settings
author_name: 				"Stefano Marra"
author_url: 				"http://www.stefanomarra.com"
author_bio: 				"Stefano Marra has built a career and reputation by breaking the rules."
author_email: 				"stefano.marra1987@gmail.com"
author_image: 				"/assets/img/authorimage.jpg"

# Social Settings
twitter_url: 				"http://twitter.com"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"

# Theme Settings
theme_analytics_id: 		"UA-28282324-1"
theme_reading_time: 		true

# Build Settings
markdown: 					kramdown
